version: "3.9"

services:
  diffusion:
    build: 
      context: ./stable-diffusion-webui
      dockerfile: Dockerfile
    container_name: 'diffusion'
    runtime: nvidia
    environment: 
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABLITIES=all
    restart: always
    tty: true
    expose: 
      - "7860"
    ports:
      - "7860:7860"